config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root 'posts#index'

  resources :comments
  get 'posts/tag' => 'posts#tag'

  resources :posts do
    resources :comments
  end

  resources :authors do
    resources :posts do
      resources :comments 
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :author

  validates :content, presence: true, length: {minimum:10,maximum:1000}
  validates :author_id, presence: true
  validates :post_id, presence: true

  def aged
    (DateTime.now - 15.minutes) > created_at
  end

  def fresh
    !aged
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @post = Post.find(index_params[:post_id])
    @comments = @post.comments 

    respond_to do |format|
      format.html
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    post = Post.find(index_params[:post_id])
    @comment = post.comments.build
    @comment.author_id = current_author_id
    @comment
  rescue Exception => e
    flash[:alert] = e.message
    raise
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    post = Post.find(comment_params[:post_id])
    @comment = post.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@comment.post), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  rescue Exception => ex
    flash[:alert] = ex.message
    raise
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    post = Post.find(update_params[:post_id])
    @comment = post.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(update_params)
        format.html { redirect_to post_path(@comment.post), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  rescue Exception => e
    flash[:alert] = e.message
    raise
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    post = Post.find(destroy_params[:post_id])
    @comment = post.comments.find(destroy_params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_path(post), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  rescue Exception => e
    flash[:alert] = e.message
    raise
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:id, :content, :author_id, :post_id)
    end

    def index_params
      params.permit(:content, :author_id, :post_id)
    end

    def destroy_params
      params.permit(:id, :content, :author_id, :post_id)
    end

    def update_params
      params.require(:comment).permit(:id, :content, :author_id, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@comment.post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :author_id %>
  <%= f.hidden_field :post_id %>

  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author_id %><br>
    <%= @comment.author.full_name %>
  </div>
  <div class="form-group">
    <%= f.label :post_id %><br>
    <%= @comment.post.title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="panel panel-primary" id="panels">
  <div class="panel-heading">
    <h3>Editing Comment</h3>
  </div>

  <%= render 'form' %>
</div>


<%= link_to 'Back', post_path(@comment.post), class: "btn" %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Author</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.created_at.strftime("%d-%m-%Y %H:%M") %></td>
        <td><%= comment&.author.full_name%></td>
        <td><%= comment&.post.title%></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<div class="panel panel-primary" id="panels">
  <div class="panel-heading">
    <h3>New Comment</h3>
  </div>

  <%= render 'form' %>
</div>

<%= link_to 'Back', post_path(@comment.post), class: "btn" %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>