config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root 'posts#index'

  resources :comments
  get 'posts/tag' => 'posts#tag'

  resources :posts do
    resources :comments
  end

  resources :authors do
    resources :posts do
      resources :comments 
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable 

  has_many :comments
  belongs_to :author

  validates :title, presence: true, length: {minimum: 5, maximum: 50}
  validates :content, presence: true, length: {minimum: 50}
  validates :author_id, presence: true
  validates_inclusion_of :published, in: [true, false] 

  accepts_nested_attributes_for :comments, allow_destroy: true, reject_if: :all_blank

  SHORT_CONTENT_LENGTH = 100

  def short_content
    content[0..SHORT_CONTENT_LENGTH]
  end

  class << self
    def unpublished
      where(published: false)
    end

    def published
      where(published: true)
    end

    def all_published?
      where(nil).all?{|p| p.published }
    end

    def tag_cloud
      Post.tag_counts_on(:tags)
    end
  end

  before_save :default_values

  def default_values
    self.published ||= false 
    true
  end

  def tags_list
    tags.map{|t| t.name }.join(',')
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  MAX_CONTENT_LENGTH = 300 
  POSTS_PER_PAGE = 5

  # GET /posts
  # GET /posts.json
  def index

    res_posts = Post.select("id, title, author_id, left(content,#{MAX_CONTENT_LENGTH}) as content, created_at, published").order( created_at: :desc )

    a_parms = get_params()

    @author_id = nil

    if( a_parms[:author_id] ) #filter posts by author
      parm_author_id = a_parms[:author_id].to_i

      raise ApplicationController::NotAuthorized, 'Access denied' if !user_signed_in?
      raise ApplicationController::NotAuthorized, "Access denied to resources from another author" if( current_author_id != parm_author_id )
      @author_id = parm_author_id 
      res_posts = res_posts.where(author_id: @author_id)
    else
      res_posts = res_posts.published
    end


    @posts = res_posts.paginate(page: params[:page], per_page: POSTS_PER_PAGE)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.published = true
  end

  # GET /posts/1/edit
  def edit
    check_access_to_author_data
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @author_id = current_user&.author&.id
    @post.author_id = @author_id
    @post.tag_list = post_params[:tag_list]

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  rescue Exception => e
    flash[:alert] = e.message
    raise
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    check_access_to_author_data

    @post.tag_list = post_params[:tag_list]

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  rescue Exception => e
    flash[:alert] = e.message
    raise
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def tag_cloud
    @tags = Post.tag_cloud
  end

  def tag
    a_parms = get_params()

    res_posts = Post.select("id, title, author_id, left(content,#{MAX_CONTENT_LENGTH}) as content, created_at, published").order( created_at: :desc )

    @author_id = nil

    res_posts = res_posts.tagged_with(a_parms[:tag], any: true)
    res_posts = res_posts.published

    @posts = res_posts.paginate(page: params[:page], per_page: POSTS_PER_PAGE)

    render action: 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :author_id, :published, :tag_list)
    end

    def get_params
      params.permit(:id, :author_id, :tag)
    end


    def check_access_to_author_data
      a_parms = get_params()
      post = Post.find(a_parms[:id])
      parm_author_id = post.author.id 

      if( current_author_id != parm_author_id )
        flash[:alert] = "Access denied"
        raise ApplicationController::NotAuthorized, flash[:alert] 
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/posts/_form.html.erb
<div >
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-check">
      <%= f.label :published %><br>
      <%= f.check_box :published, class: "form-check" %>
    </div>
    <div class="form-group">
      <%= f.label :tag_list %><br>
      <%= f.text_field :tag_list, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :content %><br>
      <%= f.text_area :content, class: "form-control", style: "width:100%;height:200px" %>
    </div>
    <div class="form-group">
      <%= f.label :created_at %><br>
      <%= f.datetime_field :created_at, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="panel panel-primary" id="panels">
  <div class="panel-heading">
    <h3>Editing Post</h3>
  </div>

  <%= render 'form' %>
</div>

<%= link_to 'Show', @post, class: "btn btn-small btn-primary" %> |
<%= link_to 'Back', posts_path, class: "btn btn-small" %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>
<% if user_signed_in? %>
  <%= link_to 'New Post', new_post_path, class: "btn btn-primary btn-small" %>
  <% if @author_id %>
    <%= link_to 'All posts', posts_path, class: "btn btn-small" %>
  <% else %>
    <%= link_to 'My Posts', author_posts_path(current_user.author), class: "btn btn-small" if current_user.author %>
  <% end %>
<% end %>

<table class="table">
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <table class="table">
            <tr>
              <% if @author_id && user_signed_in? && current_user&.author.id == post.author.id %>
                <td><b>Published:</b> <%= post.published %> </td>
              <% end %>
              <td width="100px"><%= post.created_at.strftime("%d-%m-%Y %H:%M") %></td>
              <td><%= post.tags_list %></td>
              <td width="80%"><b><%= post.title %></b></td>
              <td><i><%= post.author.full_name if post.author %></i></td>
              <td>
                <table>
                  <tr>
                    <td><%= link_to 'Show', post, class: "btn btn-primary btn-small" %></td>
                    <% if user_signed_in? %>
                      <% if current_user.id == post&.author&.user&.id %>
                        <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-success btn-small" %></td>
                        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-small" %></td>
                      <% end %>
                    <% end %>
                  </tr>
                </table>
              </td>
            </tr>
            <tr><td colspan=3><%= post.content %></td></tr>
          </table>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @posts %>

<br>

app/views/posts/new.html.erb
<div class="panel panel-primary" id="panels">
  <div class="panel-heading">
    <h3>New Post</h3>
  </div>
  <%= render 'form' %>
</div>


<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel">
<p>
  <b>Created at:</b>
  <%= @post.created_at.strftime("%d-%m-%Y %H:%M") %>

<% if user_signed_in? && current_user&.author.id == @post.author.id %>
  <p><b>Published:</b> <%= @post.published %> </p>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @post.tags_list %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author.full_name if @post.author%>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
</div>


<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary btn-small" %> |
<%= link_to 'Back', posts_path, class: "btn btn-small" %>

<hr>
<p><b>Comments:</b>
  <% if user_signed_in? %>
    <%= link_to 'New Comment', new_post_comment_path(@post), class: "btn btn-primary btn-small" %>
  <% end %>
</p>
<table class="table">
  <thead>
    <tr>
      <th>Created at</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <tr>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @post.comments.each do |c| %>
      <tr>
        <td><%= c.created_at.strftime("%d-%m-%Y %H:%M") %></td>
        <td><%= c.author.full_name %></td>
        <% if user_signed_in? && current_user&.author.id == c.author.id && c.fresh %>
          <td> <%= link_to 'Edit', edit_post_comment_path(@post,c), class: "btn btn-primary btn-small" %></td>
          <td> <%= link_to 'Destroy', [@post,c], confirm: 'Are you sure?', method: :delete, class: "btn btn-danger btn-small" %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= c.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>